collections_config:
  pages:
    path: src/content/pages
    glob:
      - '**/*.md'
    url: '/[full_slug]/'
    icon: laptop_mac
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: pages
    schemas:
      default:
        name: New Page
        path: '.cloudcannon/schemas/page.md'
        remove_extra_inputs: false
    create:
      path: '[relative_base_path]/{filename|slugify|lowercase}.md'
    new_preview_url: /
    _inputs:
      title:
        type: text
        comment: Controls the metadata title for the page.

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Data
    collections:
      - data